services:
  - type: web
    name: weather-api-poc
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: WEATHERAPI_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false